services:
  - type: web
    name: ngo-backend
    env: python
    region: oregon
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
