# Generated by Django 4.2.9 on 2026-07-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("waitlisted", "Waitlisted"),
                            ("left", "Left"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="joined",
                        max_length=20,
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="programs.program",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
                "db_table": "participation_participation",
                "ordering": ["waitlist_position", "-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "status"],
                        name="participati_program_fa20e1_idx",
                    ),
                    models.Index(
                        fields=["volunteer", "status"],
                        name="participati_volunte_74d0e6_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["joined", "waitlisted"])),
                fields=("volunteer", "program"),
                name="unique_active_participation",
            ),
        ),
    ]
