# Generated by Django 4.2.9 on 2026-07-03 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participation",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.RemoveConstraint(
            model_name="participation",
            name="unique_active_participation",
        ),
        migrations.AddField(
            model_name="participation",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Optional message from volunteer when requesting to join",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="requested_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participation",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participation",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("joined", "Joined"),
                    ("waitlisted", "Waitlisted"),
                    ("rejected", "Rejected"),
                    ("left", "Left"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "joined", "waitlisted"])),
                fields=("volunteer", "program"),
                name="unique_active_participation",
            ),
        ),
    ]
