# Generated by Django 4.2.9 on 2026-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participation", "0002_alter_participation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
