# Generated by Django 4.2.9 on 2026-07-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("program_created", "Program Created"),
                            ("program_updated", "Program Updated"),
                            ("program_deleted", "Program Deleted"),
                            ("volunteer_joined", "Volunteer Joined"),
                            ("volunteer_left", "Volunteer Left"),
                            ("volunteer_waitlisted", "Volunteer Waitlisted"),
                            ("waitlist_promoted", "Waitlist Promoted"),
                            ("ngo_approved", "NGO Approved"),
                            ("ngo_rejected", "NGO Rejected"),
                            ("certificate_generated", "Certificate Generated"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activity_activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_ac_user_id_66823d_idx",
                    )
                ],
            },
        ),
    ]
